# Generated by Django 6.0.5 on 2026-08-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhattaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Person / Customer Name (e.g. Ali Khan)', max_length=200)),
                ('entry_type', models.CharField(choices=[('lene_hain', 'Lene Hain (Receivable)'), ('dene_hain', 'Dene Hain (Payable)')], default='lene_hain', help_text='Lene Hain or Dene Hain', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in PKR', max_digits=12)),
                ('note', models.TextField(blank=True, help_text='Transaction description or remarks')),
                ('date', models.DateField(help_text='Transaction Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled / Paid')], default='pending', max_length=20)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
