# Generated by Django 5.2.14 on 2026-05-30 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_phone', models.CharField(max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dealer_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='purchase_docs/')),
                ('purchase_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.car')),
            ],
        ),
    ]
