# Generated by Django 6.0.5 on 2026-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sale_videos/'),
        ),
    ]
