# Generated by Django 6.0.5 on 2026-08-17 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Payment Received'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('pending', 'Pending')], default='pending', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Down Payment'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='installment_months',
            field=models.IntegerField(default=0, verbose_name='Total Installments'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Installment Amount'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('installment', 'Installment')], default='cash', max_length=20, verbose_name='Sale Type'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sale Date'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Sale Price'),
        ),
    ]
