# Generated by Django 6.0.5 on 2026-08-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_carrepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Rental Date')),
                ('city', models.CharField(help_text='Destination / City', max_length=150)),
                ('total_rent', models.DecimalField(decimal_places=2, help_text='Total Rent Amount (PKR)', max_digits=12)),
                ('petrol_expense', models.DecimalField(decimal_places=2, default=0, help_text='Petrol Expense (PKR)', max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, help_text='Total Profit (PKR)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional rental notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='inventory.car')),
            ],
        ),
    ]
